### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [EPFL-VILAB/ViPer#2]
Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.17365 (feel free to claim the paper so that it appears at your HF account!).

However there are a couple of things which could improve the discoverability of your work, which I've listed below.

## Link models to the paper

I see the model is already on the hub, here:
* https://huggingface.co/EPFL-VILAB/VPE-ViPer
* https://huggingface.co/EPFL-VILAB/Metric-ViPer

Really nice to see the model cards 🤗 

It would be great to link the models to the paper, see here on how to do that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

## Making download stats work for your models

Currently, download stats aren't tracked for your models. This is due to the repos not containing a config.json, which is used to count downloads. Could you consider pushing the model config as well?

## Link Space to the paper

I see you have a demo at https://huggingface.co/spaces/EPFL-VILAB/ViPer, it would be awesome to link it to the paper! See here on how to do that: https://huggingface.co/docs/hub/en/paper-pages#linking-a-paper-to-a-model-dataset-or-space

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by sogandstormesalehi** [comment]
Thanks for reaching out and for the helpful suggestions Niels! All done!

Best,

**Comment by NielsRogge** [comment]
Awesome! Would be great to link the 🤗 artifacts (or paper page URL) in the README of this repo.

I also opened https://huggingface.co/EPFL-VILAB/Metric-ViPer/discussions/1 for some misc improvements
