### ISSUE TITLE
Training Datasets

### ISSUE THREAD

**Issue by dain5832** [EPFL-VILAB/ViPer#5]
Hi,
I wonder if you are willing to release the datasets you used for VPE training.
It would be wonderful if I could get the data of the 5000 agents mentioned in the paper, especially 50 likes and dislikes attributes and the generated image for each agent.

Thanks!

**Comment by sogandstormesalehi** [comment]
Thank you for your interest! We currently don't plan on releasing the data, as it's not yet ready for publication.  However, we have released the visual attributes in the supplementary material, and the generation process is described in the paper, so the results can be reproduced. We appreciate your understanding!
Best,
